version: '3.2'
services:
  elasticsearch:
    image: elasticsearch:latest
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
        ES_NET_HOST: "0.0.0.0"
  kibana:
    image: kibana:latest
    restart: "always"
    ports:
      - "5601:5601"
